[build]
  command = "gatsby build"
  [build.environment]
    GATSBY_TILER = "https://tiler.freesewing.org/"
    GATSBY_ALGOLIA_API_ID = "MA0Y5A2PF0"
    GATSBY_ALGOLIA_SEARCH_KEY = "278751992e7a54c20c49a3c04f1c80fe"
    GATSBY_CONTEXT = "production"
